// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7lRY_RnOgVI_M6GV2p7Lh5iI27DxOgvU',
    appId: '1:533762610231:web:e008a37f4c7b52e0d25bb2',
    messagingSenderId: '533762610231',
    projectId: 'karma-gurme',
    authDomain: 'karma-gurme.firebaseapp.com',
    storageBucket: 'karma-gurme.appspot.com',
    measurementId: 'G-MLHR5S1KW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5Nvoo3VG7QD9mjuniPXelmAJdfrXNN9o',
    appId: '1:533762610231:android:6470c653c1ede8c6d25bb2',
    messagingSenderId: '533762610231',
    projectId: 'karma-gurme',
    storageBucket: 'karma-gurme.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB932oRa3QlCV4VuupUWV_5u7mGPJ68brk',
    appId: '1:533762610231:ios:48d027fcd3839e5ad25bb2',
    messagingSenderId: '533762610231',
    projectId: 'karma-gurme',
    storageBucket: 'karma-gurme.appspot.com',
    iosClientId:
        '533762610231-lrvh56j5rdo146m8cmaata8ln78gklu4.apps.googleusercontent.com',
    iosBundleId: 'com.karmaf154.gurme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB932oRa3QlCV4VuupUWV_5u7mGPJ68brk',
    appId: '1:533762610231:ios:37817801f83b3422d25bb2',
    messagingSenderId: '533762610231',
    projectId: 'karma-gurme',
    storageBucket: 'karma-gurme.appspot.com',
    iosClientId:
        '533762610231-p4j3miml2srtth2vuvl04vaqar5gfeh5.apps.googleusercontent.com',
    iosBundleId: 'com.karmaf154.gurme.RunnerTests',
  );
}
